name: JobClassSystem
version: 1.0.0
main: com.mr.jobclass.JobClassPlugin
api-version: 1.20
description: 직업/문파/헌터 시스템 플러그인
depend:
  - DimensionCore
  - StatSystem
commands:
  job:
    description: 직업 조회 및 선택
    usage: /job [select <직업>|info]
